### ISSUE TITLE
Bug mentioned in https://doi.org/10.3389/fnhum.2020.00246

### ISSUE THREAD

**Issue by giorgioganis** [arnodelorme/neurofeedbacklab#2]
Hi,

What was the bug you mentioned in your Frontiers paper ( https://doi.org/10.3389/fnhum.2020.00246 )?  _"Note that a bug in the program made it so that the state of the ASR filter was not propagated properly from one data block to the next, generating brief small signal discontinuities."_ . 
Is this a bug within the ASR code itself or in the way it was applied to the incoming data in nfblab_process? I was going through your code and so I would like to make sure I understand where the glitch was. 

Thanks much!

-Giorgio

**Comment by arnodelorme** [comment]
It is the way ASR was applied to the incoming data in nfblab_process? This bug was fixed a long time ago, and the output file processed has been compared to the input stream (which can also be a file).
