### ISSUE TITLE
Can't find nfblab_options.m

### ISSUE THREAD

**Issue by nicoa47** [arnodelorme/neurofeedbacklab#3]
Hi,
I can't find the file `nfblab_options.m` you are talking about in this video:
https://www.youtube.com/watch?v=hGiupsdwMi4
Can you upload a current working version of the file again? Alternatively, did it git replaced with another file maybe?

Thank you!
Nico

**Comment by Colton127** [comment]
A bit late to the party, but for future reference the options are now in `nfblab_setfields.m`
