### ISSUE TITLE
Selecting a channel and frequency range via freqprocess

### ISSUE THREAD

**Issue by Colton127** [arnodelorme/neurofeedbacklab#4]
Hello,

Thank you a lot for this wonderful project. I have had much success developing basic neurofeedback applications and find the TCP/IP connection really convenient.

I have a question for purposes of clarification and to possibly help anyone else who finds themselves using neurofeedbacklab.

Within `nfblab_setfields.m` under `freqprocess` you specify the channel(s) to listen to and the spectral power for the specified channel is outputted.

Can you please clarify how to select a channel _and_ frequency range? I'm using a muse headset, so I have four channels in total. If I set a single freqrange, the maximum channel number I can listen to is 4. If I set two frequency ranges, the maximum channel number I can listen to is 8. 

For example:

`'chans'          [1:4]`
`'freqrange'      { [3.5 6.5], [38 42]}`

Is this the proper way of selecting a channel and frequency range?

`'measure'   'freqprocess'    struct('thetaChan2', @(x)x(2), 'thetaChan3', @(x)x(3), 'gammaChan1', @(x)x(5), 'gammaChan2', @(x)x(6))`

Whereas 2 is the second channel of the first frequency range, and 6 is the second channel of the second frequency range.

Is this correct, or am I missing something?

Thank you.

**Comment by arnodelorme** [comment]
Yes, this is correct. Apologies for the late reply. This has now been documented.
