### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by gar1ma** [arnodelorme/neurofeedbacklab#6]
The Psychtoolbox visual protocol doesn't work in the new file structure (It gives an error with the Screen command). I have updated it according to the official format described, yet it doesn't display the visual.
I rechecked the validity of the code by using it in the older/previous file structure of NeurofeedbackLab and it works there but only in offline mode. Can you please check the issue with the visual output in the current file structure?

**Comment by arnodelorme** [comment]
I have made some changes and it worked with the latest version of the psycho toolbox Psychtoolbox-3-3.0.19.0 for me on Mac OSX.
