### ISSUE TITLE
Getting ASR to work?

### ISSUE THREAD

**Issue by sam-neuroberts** [arnodelorme/neurofeedbacklab#9]
Hi I'm continuing the thread I raised on the eeglab mailing list.

I managed to record a baseline with `asrFlag` to `true` and that went okay I didn't get any errors, but when I then tried to run `nfblab_process` in `trial` mode, I get the following:

`Loading baseline ASR file data_nfblab_2024-11-14_09-45_asr_filter.mat...
eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
Feedback "Streaming" sent to client (if any)
Error using  / 
Matrix dimensions must agree.

Error in asr_process (line 138)
splits = ceil((C*C*S*8*8 + C*C*8*S/stepsize + C*S*8*2 + S*8*5) / (maxmem*1024*1024 - C*C*P*8*3)); % Mysterious. More memory available, less 'splits'

Error in nfblab_process (line 581)
                [chunkFilt(nonEventChans,:), stateAsr]= asr_process(chunkFilt(nonEventChans,:), g.input.srateHardware, stateAsr, [],[],[],[],size(g.input.chans));
 `

If it helps to know I'm running this on BioSemi at 1024Hz, but also had the same issues when I ran it on OpenBCI's simulated data at 250Hz.

Any advice on how to remedy this to get the ASR to work is very appreciated.
Best Regards 
-Sam.

**Comment by arnodelorme** [comment]
Would you mind to provide your .mat file data_nfblab_2024-11-14_09-45_asr_filter.mat

**Comment by sam-neuroberts** [comment]
Hi Arno,
Thanks!
So GitHub doesn't natively support .mat but here's a OneDrive Link where you can download the file: [Link kere](https://livemanchesterac-my.sharepoint.com/:u:/g/personal/sam_roberts-4_postgrad_manchester_ac_uk/ETEPjcD-nv9KsnOXQJw8Pt8BhcVDVOG4colybxK3Iwzm-g?e=t5OR67)

**Comment by arnodelorme** [comment]
The data file does contain ASR filtering values. Another possibility is that the data has changed size. I would need to see the error in action, and I do not really have the bandwidth for that. I suggest to restart everything (delete all files) and maybe the error will go away if it is an issue with changing the number of channels.

**Comment by sam-neuroberts** [comment]
No worries, I appreciate the time you've given me. I went from scratch and am still having issues though, do you know of any expert users of the toolbox that I could contact instead to try and resolve my issue, and then I'll append the solution to this thread later?

**Comment by arnodelorme** [comment]
I know some people but everyone is very busy. Maybe try on Upwork. If you zip your entire folder with neurofeedbacklab, tell me to run a specific function, and see how it crashes, I will give it a try.
